apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi-container
          image: ghcr.io/tmteameod/smhrd_mlops:latest  # 웹훅 실행 시마다 새로운 태그 적용됨
          ports:
            - containerPort: 80
