apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # 외부에서 접근할 수 있는 NodePort 번호
  type: NodePort  # 서비스 유형을 NodePort로 설정
